name: schedule-check
on: 
  schedule:
   - cron: "23 06 * * *"

  workflow_dispatch:

jobs:
  gdext-check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.checks.outputs.changed }} 
    steps:
      - name: Checking for gdext changes
        id: checks
        run: |
          curled=$(curl -s https://api.github.com/repos/godot-rust/gdext/commits/heads/master)
          changed=$(echo $curled | jq -r "((now - (.commit.author.date | fromdateiso8601)) / (60*60*25) | trunc)")
          echo "changed=${changed}" >> "$GITHUB_OUTPUT"

  gdext-sha:
    needs: gdext-check
    uses: ./.github/workflows/reusable_gdext_sha.yaml

  debug-test:
    needs: gdext-check
    if: needs.gdext-check.outputs.changed == '0'
    uses: ./.github/workflows/reusable_tests.yaml
    with:
      godot-version: 4.2
      release: false

  release-test:
    needs: [gdext-check, debug-test]
    if: needs.gdext-check.outputs.changed == '0'
    uses: ./.github/workflows/reusable_tests.yaml
    with:
      godot-version: 4.2
      release: true

  gdext-compat-badge:
    needs: [gdext-sha, release-test]
    uses: ./.github/workflows/reusable_gdext_badge.yaml
    with:
      gdext_sha: ${{ needs.gdext-sha.outputs.sha }}  
