name: gdext-latest-success
on: 
  workflow_run:
    workflows:
      - "Crate tests"
    types: 
      - completed
    branches: 
      - master

jobs:
  gdext-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get gdext latest commit
        id: gdext_commit
        shell: bash
        run: |
          sha=$(curl -s https://api.github.com/repos/godot-rust/gdext/commits/heads/master | jq -r ".sha")
          echo "SHORT_SHA=${sha:0:10}" >> $GITHUB_ENV

      - name: gdext Commit badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: gdext_latest_success
          LABEL: 'Latest compatible gdext'
          STATUS: ${{ env.SHORT_SHA }}
          COLOR: E9D105
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
