name: Get gdext short sha

on:
  workflow_call:
    outputs:
      sha:
        description: "Short SHA of latest gdext commit"
        value: ${{ jobs.get_sha.outputs.sha }}

jobs:
  get_sha:
    name: gdext commit sha
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.gdext_commit.outputs.short_sha }}

    steps:
      - name: Get gdext latest commit
        id: gdext_commit
        shell: bash
        run: |
          sha=$(curl -s https://api.github.com/repos/godot-rust/gdext/commits/heads/master | jq -r ".sha")
          echo "short_sha=${sha:0:10}" >> $GITHUB_OUTPUT